services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./learn_service:/service
    environment:
      - DB_HOST=database
      - DB_NAME=dbservice
      - DB_USER=admin
      - DB_PASSWORD=admin

    command: >
       sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbservice
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./learn_service:/service
    links:
      - redis
    depends_on:
      - redis
